name: ZachWeismann
favicon: null
layout_spectrum: 0.39742598216980696
typography_spectrum: 0.13112435396760702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.04418250289745629
  lightness: 0.23161609354428947
  saturation: 0.2795820136088878
  rhythmicContrast: 0.6752020199783146
purpose: []
